// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	AUTH_DB: D1Database;
	MAIN_DB: D1Database;
	ASSETS: Fetcher;
}
