export const LOADING_MESSAGES = [
  "Destination in sight...",
  "Bribing the login gods...",
  "Untangling the internet cables...",
  "Feeding the hamsters that power our servers...",
  "Waiting for the Wi-Fi to wake up...",
  "Convincing your browser to cooperate...",
  "Googling 'how to login'...",
  "Dusting off your account...",
  "Waking up the login fairy...",
  "Performing ancient login rituals...",
  "Consulting the magic 8-ball...",
  "Summoning your digital self...",
  "Negotiating with the firewall...",
  "Teaching robots to trust you...",
  "Polishing your virtual doorknob...",
  "Searching for your lost password in the couch cushions...",
  "Reversing the polarity...",
  "Spinning up the flux capacitor...",
  "Loading your awesomeness...",
  "Calibrating the cool factor...",
  "Initializing maximum security mode...",
  "Activating VIP treatment...",
];

export const FUNNY_VERIFICATION_MESSAGES = [
  "Confirming you have a soul...",
  "Scanning for signs of humanity...",
  "Verifying emotional capacity...",
  "Running empathy diagnostics...",
  "Making sure you can't compress your thoughts into a zip file...",
  "Confirming you don't automatically update overnight...",
  "Confirming you don't speak fluent JavaScript...",
  "Confirming you don't speak fluent C++...",
  "Verifying you have feelings...",
  "Confirming you don't run on lithium batteries...",
];
