import type { InvalidInputs, TopicalData } from "./types";

export const TOPICAL_DATA: TopicalData[] = [
  {
    curriculum: "CIE A-LEVEL",
    coverImage: "/assets/cover/alevels-logo1.jpg",
    subject: [
      {
        coverImage: "/assets/cover/Physics (9702).jpg",
        code: "Physics (9702)",
        topic: [
          "PHYSICAL QUANTITIES & UNITS",
          "MEASUREMENT TECHNIQUES",
          "KINEMATICS",
          "DYNAMICS",
          "FORCES, DENSITY & PRESSURE",
          "WORK, ENERGY & POWER",
          "MOTION IN A CIRCLE",
          "GRAVITATIONAL FIELDS",
          "DEFORMATION OF SOLIDS",
          "IDEAL GASES",
          "TEMPERATURE",
          "THERMAL PROPERTIES OF MATERIALS",
          "OSCILLATIONS",
          "WAVES",
          "SUPERPOSITION",
          "COMMUNICATION",
          "ELECTRIC FIELDS",
          "CAPACITANCE",
          "CURRENT OF ELECTRICITY",
          "D.C. CIRCUITS",
          "ELECTRONICS",
          "MAGNETIC FIELDS",
          "ELECTROMAGNETIC INDUCTION",
          "ALTERNATING CURRENTS",
          "QUANTUM PHYSICS",
          "PARTICLE & NUCLEAR PHYSICS",
          "MEDICAL IMAGING",
          "ASTRONOMY & COSMOLOGY",
        ],
        year: [
          2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
          2013, 2012, 2011, 2010, 2009,
        ],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Chemistry (9701).jpg",
        code: "Chemistry (9701)",
        topic: [
          "ATOMS, MOLECULES & STOICHIOMETRY",
          "ATOMIC STRUCTURE",
          "CHEMICAL BONDING",
          "STATES OF MATTER",
          "CHEMICAL ENERGETICS",
          "ELECTROCHEMISTRY",
          "EQUILIBRIA",
          "REACTION KINETICS",
          "THE PERIODIC TABLE: CHEMICAL PERIODICITY",
          "GROUP 2",
          "GROUP 17",
          "AN INTRODUCTION TO THE CHEMISTRY OF TRANSITION ELEMENTS",
          "NITROGEN & SULFUR",
          "AN INTRODUCTION TO ORGANIC CHEMISTRY",
          "HYDROCARBONS",
          "HALOGEN DERIVATIVES",
          "HYDROXY COMPOUNDS",
          "CARBONYL COMPOUNDS",
          "CARBOXYLIC ACIDS AND DERIVATIVES",
          "NITROGEN COMPOUNDS",
          "POLYMERISATION",
          "ANALYTICAL TECHNIQUES",
          "ORGANIC SYNTHESIS",
        ],
        year: [
          2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
          2013, 2012, 2011, 2010, 2009,
        ],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Biology (9700).jpg",
        code: "Biology (9700)",
        topic: [
          "CELL STRUCTURE",
          "BIOLOGICAL MOLECULES",
          "ENZYMES",
          "CELL MEMBRANES AND TRANSPORT",
          "THE MITOTIC CELL CYCLE",
          "NUCLEIC ACIDS AND PROTEIN SYNTHESIS",
          "TRANSPORT IN PLANTS",
          "TRANSPORT IN MAMMALS",
          "GAS EXCHANGE AND SMOKING",
          "INFECTIOUS DISEASE",
          "IMMUNITY",
          "ENERGY AND RESPIRATION",
          "PHOTOSYNTHESIS",
          "HOMEOSTASIS",
          "CONTROL AND CO-ORDINATION",
          "INHERITED CHANGE",
          "SELECTION AND EVOLUTION",
          "BIODIVERSITY, CLASSIFICATION AND CONSERVATION",
          "GENETIC TECHNOLOGY",
        ],
        year: [
          2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
          2013, 2012, 2011, 2010, 2009,
        ],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Pure 1 (9709).jpg",
        code: "Pure Mathematics 1 (9709)",
        topic: ["Algebra", "Geometry", "Calculus", "Statistics"],
        year: [2024, 2023, 2022, 2021],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Mechanics (9709).jpg",
        code: "Mechanics (9709)",
        topic: ["Algebra", "Geometry", "Calculus", "Statistics"],
        year: [2024, 2023, 2022, 2021],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Probability & Statistics 1 (9709).jpg",
        code: "Probability & Statistics 1 (9709)",
        topic: ["Algebra", "Geometry", "Calculus", "Statistics"],
        year: [2024, 2023, 2022, 2021],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Probability & Statistics 2 (9709).jpg",
        code: "Probability & Statistics 2 (9709)",
        topic: ["Algebra", "Geometry", "Calculus", "Statistics"],
        year: [2024, 2023, 2022, 2021],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
      {
        coverImage: "/assets/cover/Pure 2&3 (9709).jpg",
        code: "Pure Mathematics 2 & 3 (9709)",
        topic: ["Algebra", "Geometry", "Calculus", "Statistics"],
        year: [2024, 2023, 2022, 2021],
        paperType: [1, 2, 3, 4],
        season: ["Summer", "Winter"],
      },
    ],
  },
];

export const FILTERS_CACHE_KEY = "noteoverflow-filters-cache";

export const INVALID_INPUTS_DEFAULT: InvalidInputs = {
  curriculum: false,
  subject: false,
  topic: false,
  year: false,
  paperType: false,
  season: false,
};

export const PAGE_SIZE = 50;

export const DEFAULT_NUMBER_OF_COLUMNS = 3;

export const COLUMN_BREAKPOINTS = {
  1: { 0: 1 },
  2: { 0: 1, 1: 2 },
  3: { 0: 1, 1: 2, 500: 3 },
  4: { 0: 1, 1: 2, 500: 3, 790: 4 },
  5: { 0: 1, 1: 2, 500: 3, 790: 4, 900: 5 },
};
